package org.hkijena.mcat.api;

import org.hkijena.mcat.utils.JsonUtils;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Encapsulates a result generated by a {@link MCATRun}
 */
public class MCATResult {
    private Path outputFolder;
    private MCATProject project;

    public MCATResult(Path outputFolder) {
        this.outputFolder = outputFolder;
    }

    public Path getOutputFolder() {
        return outputFolder;
    }

    public MCATProject getProject() {
        return project;
    }
}
